version: '3'
services:
  web:
    image: nginx:latest
    container_name: backend
    ports:
      - "8485:80"
    volumes:
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/html:/usr/share/nginx/html
